# Generated by Django 3.0.8 on 2020-08-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profilepicture',
            field=models.ImageField(blank=True, default='media/tutorProfile/profile.png', null=True, upload_to='media/studentprofile'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='profilepicture',
            field=models.ImageField(blank=True, default='media/tutorProfile/profile.png', null=True, upload_to='media/tutorProfile'),
        ),
    ]
