# Generated by Django 3.0.8 on 2020-09-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0005_tutorprofile_merchantid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chatroom',
        ),
    ]
