# Generated by Django 3.0.8 on 2020-09-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0009_chapterresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterresource',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapterrestutor', to='University.TutorProfile'),
            preserve_default=False,
        ),
    ]
