# Generated by Django 3.0.8 on 2020-09-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0006_remove_question_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='qus_course', to='University.Course'),
            preserve_default=False,
        ),
    ]
