# Generated by Django 3.0.8 on 2020-09-27 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0008_remove_question_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, default='tes', null=True, upload_to='media/ChapterResource')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapterresorces', to='University.Chapters')),
            ],
        ),
    ]
